Add basic test for commonServer.ConfigSpec
The Packer SDK relies on encoding/gob for serializing hcldec.ObjectSpec
over RPC. The added test check that types implementing the HCL2Speccer
interface can be encoded/decoded without issue.

Starting in go-cty v1.11.0 support for encoding/gob was removed, which
causes the added tests to fail. This is expected and is meant to help
catch potential regressions moving forward.

Test results running go-cty v1.10.0
```
--- PASS: TestCommonServer_ConfigSpec (0.00s)
    --- PASS: TestCommonServer_ConfigSpec/Builder_Component_Server (0.00s)
    --- PASS: TestCommonServer_ConfigSpec/Datasource_Component_Server (0.00s)
    --- PASS: TestCommonServer_ConfigSpec/Provisioner_Component_Server (0.00s)
=== RUN   TestCommunicatorRPC
```

Test results running go-cty v1.13.1
```
2023/04/21 11:28:05 [WARN] Client is closing mux
--- FAIL: TestCommonServer_ConfigSpec (0.00s)
    --- FAIL: TestCommonServer_ConfigSpec/Builder_Component_Server (0.00s)
panic: ConfigSpec failed: gob: type cty.Type has no exported fields [recovered]
        panic: ConfigSpec failed: gob: type cty.Type has no exported fields

goroutine 299 [running]:
testing.tRunner.func1.2({0x10524fb60, 0x14000486530})
        /usr/local/go/src/testing/testing.go:1389 +0x1c8
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1392 +0x384
panic({0x10524fb60, 0x14000486530})
        /usr/local/go/src/runtime/panic.go:838 +0x204
github.com/hashicorp/packer-plugin-sdk/rpc.(*commonClient).ConfigSpec(0x14000475f08)
        /Users/dev/Development/packer-plugin-sdk/rpc/common.go:48 +0x24c
github.com/hashicorp/packer-plugin-sdk/rpc.TestCommonServer_ConfigSpec.func1(0x140004e5860)
        /Users/dev/Development/packer-plugin-sdk/rpc/common_test.go:44 +0x10c
testing.tRunner(0x140004e5860, 0x14000483dd0)
        /usr/local/go/src/testing/testing.go:1439 +0x110
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1486 +0x300
FAIL    github.com/hashicorp/packer-plugin-sdk/rpc      0.796s
```